version: '3'
services:
  redis:
    image: redis:alpine
    ports:
        - "6379:6379/tcp"
    networks:
      - frontend
    deploy:
      mode: replicatedaria
      replicas: 4
      update_config:    # 配置如何更新服务
        parallelism: 2  # 每次要更新的容器数量
        delay: 10s      # 更新下一组容器前要等待的时间
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

networks:
  frontend: