FROM imxieke/archlinux:base
LABEL MAINTAINER="Cloudflying" \
        MAIL="<oss@live.hk>"

RUN pacman -Syyu --noconfirm \
    && pacman -S --noconfirm --force gcc make cmake neovim git \
    && rm -fr /var/cache/pacman/pkg/* \
    && pacman -Scc --noconfirm \
    && rm -fr /var/lib/pacman/*

CMD /bin/bash