version: '3'
services:
  redis:
    image: registry.cn-hongkong.aliyuncs.com/imxieke/aria2:latest
    ports:
      - "6800:6800/tcp"
      - "8080:8080/tcp"
    volumes:
      - $HOME/Downloads:/downloads
    environment:
      ARIA2_PORT: 6800
      ARIA2_SECRET: aria2pwd
      WEBUI_PORT: 8080
    restart: on-failur
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s