version: '3.1'

services:

  mysql:
    image: mysql:5.7.29
    ports:
        - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '19960318'
      MYSQL_USER: 'apiset'
      MYSQL_PASS: '19960318'
    volumes:
      - "/Users/imxieke/Code/Storage/mysql:/var/lib/mysql"
      - "./conf.d/5.7.cnf:/etc/my.cnf"