# Ubuntu 14.04
FROM ubuntu:trusty

LABEL MAINTAINER="Cloudflying" \
        MAIL="oss@live.hk"

ENV ENV PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
	&& apt update \
	&& apt-get upgrade -y \
	&& apt-get autoremove -y \
	&& apt-get clean all \
	&& rm -fr /var/lib/apt/lists/*

CMD ['/bin/bash']