# Ubuntu 14.04
FROM ubuntu:trusty

LABEL MAINTAINER="Cloudflying" \
        MAIL="oss@live.hk"

ENV ENV PATH="/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
RUN apt update \
	&& apt-get upgrade -y \
	&& apt-get autoremove -y \
	&& apt-get clean all \
	&& rm -fr /var/lib/apt/lists/*

CMD ['/bin/bash']